language: node_js
node_js:
 - "0.10"
install:
 - git checkout dev-master
 - npm install
before_script:
 - phantomjs --version
 - mocha-phantomjs --version
 - grunt &
 - sleep 5
script:
 - mocha-phantomjs test/index.html